title: "Tim Baron" # your name (or website title) here
logo: "/images/timandsqueaky.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an informational professional interested in data science, mathematics, physical sciences, libraries, technical writing, databases, and computer programming.
  <br><br/>  
  MLIS - Library & Information Science<br/>
  Wayne State University
  <br><br/>  
  BS - Maj: Mathematics Min: General Sciences<br/>
  Eastern Michigan University
  <br><br/>  
  BS - Maj: English Min: History <br/>
  Eastern Michigan University 
  <br><br/>  
  <br/>
  </br>
  <a href="https://www.linkedin.com/in/timbaroninfopro/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
